"""property shortlisted_at

Revision ID: 7f65d3f62c61
Revises: 313e03064089
Create Date: 2026-09-04 21:56:17.621278
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op

revision = '7f65d3f62c61'
down_revision = '313e03064089'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shortlisted_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.create_index(batch_op.f('ix_properties_shortlisted_at'), ['shortlisted_at'], unique=False)

    # ### end Alembic commands ###

    # The Merkliste supersedes the old "shortlist" triage state (see
    # docs/superpowers/specs/2026-09-04-ui-refinements-design.md, section 2):
    # honour the reader's intent instead of quietly dropping it.
    op.execute(
        "UPDATE properties SET shortlisted_at = updated_at, user_state = NULL "
        "WHERE user_state = 'shortlist'"
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_properties_shortlisted_at'))
        batch_op.drop_column('shortlisted_at')

    # ### end Alembic commands ###
