"""property user_title

Revision ID: 8670e2b33adc
Revises: 7f65d3f62c61
Create Date: 2026-09-23 21:29:27.688211
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op

revision = '8670e2b33adc'
down_revision = '7f65d3f62c61'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_title', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.drop_column('user_title')

    # ### end Alembic commands ###
