"""source listing_ttl_days

Revision ID: 313e03064089
Revises: a78c19944d2d
Create Date: 2026-09-03 20:19:51.825503
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op

revision = '313e03064089'
down_revision = 'a78c19944d2d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sources', schema=None) as batch_op:
        batch_op.add_column(sa.Column('listing_ttl_days', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sources', schema=None) as batch_op:
        batch_op.drop_column('listing_ttl_days')

    # ### end Alembic commands ###
