"""baseline from current models

Revision ID: a78c19944d2d
Revises: 
Create Date: 2026-09-03 19:33:57.779144
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = 'a78c19944d2d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('geo_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('key', sa.String(length=500), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kind', 'key', name='uq_geo_cache_kind_key')
    )
    with op.batch_alter_table('geo_cache', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_geo_cache_key'), ['key'], unique=False)

    op.create_table('properties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=24), nullable=False),
    sa.Column('canonical_title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('street', sa.String(length=200), nullable=True),
    sa.Column('postcode', sa.String(length=16), nullable=True),
    sa.Column('town', sa.String(length=160), nullable=True),
    sa.Column('district', sa.String(length=160), nullable=True),
    sa.Column('state', sa.String(length=80), nullable=True),
    sa.Column('country', sa.String(length=2), nullable=False),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lon', sa.Float(), nullable=True),
    sa.Column('geo_precision', sa.String(length=16), nullable=False),
    sa.Column('distance_air_km', sa.Float(), nullable=True),
    sa.Column('distance_driving_km', sa.Float(), nullable=True),
    sa.Column('distance_driving_minutes', sa.Float(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('price_type', sa.String(length=16), nullable=False),
    sa.Column('price_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('price_first', sa.Float(), nullable=True),
    sa.Column('price_reduction_count', sa.Integer(), nullable=False),
    sa.Column('land_sqm', sa.Float(), nullable=True),
    sa.Column('living_sqm', sa.Float(), nullable=True),
    sa.Column('usable_sqm', sa.Float(), nullable=True),
    sa.Column('rooms', sa.Float(), nullable=True),
    sa.Column('year_built', sa.Integer(), nullable=True),
    sa.Column('condition', sa.String(length=32), nullable=True),
    sa.Column('property_type', sa.String(length=80), nullable=True),
    sa.Column('building_features', sa.JSON(), nullable=False),
    sa.Column('outbuildings', sa.JSON(), nullable=False),
    sa.Column('special_features', sa.JSON(), nullable=False),
    sa.Column('exclusion_flags', sa.JSON(), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('listing_status', sa.String(length=24), nullable=False),
    sa.Column('verification_status', sa.String(length=16), nullable=False),
    sa.Column('first_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_verified', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('removed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_foreclosure', sa.Boolean(), nullable=False),
    sa.Column('is_monument', sa.Boolean(), nullable=False),
    sa.Column('is_private_seller', sa.Boolean(), nullable=False),
    sa.Column('is_off_market_signal', sa.Boolean(), nullable=False),
    sa.Column('fingerprint', sa.String(length=64), nullable=True),
    sa.Column('merged_into_id', sa.Integer(), nullable=True),
    sa.Column('llm_summary', sa.Text(), nullable=True),
    sa.Column('llm_risks', sa.JSON(), nullable=False),
    sa.Column('llm_reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_state', sa.String(length=24), nullable=True),
    sa.Column('user_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['merged_into_id'], ['properties.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.create_index('ix_properties_active', ['listing_status', 'distance_air_km'], unique=False)
        batch_op.create_index(batch_op.f('ix_properties_distance_air_km'), ['distance_air_km'], unique=False)
        batch_op.create_index(batch_op.f('ix_properties_fingerprint'), ['fingerprint'], unique=False)
        batch_op.create_index('ix_properties_geo', ['lat', 'lon'], unique=False)
        batch_op.create_index(batch_op.f('ix_properties_land_sqm'), ['land_sqm'], unique=False)
        batch_op.create_index(batch_op.f('ix_properties_listing_status'), ['listing_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_properties_postcode'), ['postcode'], unique=False)
        batch_op.create_index(batch_op.f('ix_properties_price'), ['price'], unique=False)
        batch_op.create_index(batch_op.f('ix_properties_property_type'), ['property_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_properties_public_id'), ['public_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_properties_town'), ['town'], unique=False)
        batch_op.create_index(batch_op.f('ix_properties_user_state'), ['user_state'], unique=False)
        batch_op.create_index(batch_op.f('ix_properties_verification_status'), ['verification_status'], unique=False)

    op.create_table('search_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('profile_hash', sa.String(length=32), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('search_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_search_profiles_profile_hash'), ['profile_hash'], unique=False)

    op.create_table('search_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('trigger', sa.String(length=24), nullable=False),
    sa.Column('profile_hash', sa.String(length=32), nullable=True),
    sa.Column('stage', sa.String(length=24), nullable=True),
    sa.Column('sources_run', sa.Integer(), nullable=False),
    sa.Column('listings_seen', sa.Integer(), nullable=False),
    sa.Column('properties_new', sa.Integer(), nullable=False),
    sa.Column('properties_updated', sa.Integer(), nullable=False),
    sa.Column('price_changes', sa.Integer(), nullable=False),
    sa.Column('removed', sa.Integer(), nullable=False),
    sa.Column('duplicates_merged', sa.Integer(), nullable=False),
    sa.Column('log', sa.JSON(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('base_url', sa.String(length=500), nullable=True),
    sa.Column('region', sa.String(length=120), nullable=True),
    sa.Column('reliability', sa.Float(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('rate_limit_seconds', sa.Float(), nullable=False),
    sa.Column('respect_robots', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('consecutive_failures', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sources', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sources_key'), ['key'], unique=True)

    op.create_table('cost_estimates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('purchase_price', sa.Float(), nullable=True),
    sa.Column('acquisition_costs', sa.Float(), nullable=True),
    sa.Column('renovation_low', sa.Float(), nullable=True),
    sa.Column('renovation_mid', sa.Float(), nullable=True),
    sa.Column('renovation_high', sa.Float(), nullable=True),
    sa.Column('immediate_capex', sa.Float(), nullable=True),
    sa.Column('total_low', sa.Float(), nullable=True),
    sa.Column('total_mid', sa.Float(), nullable=True),
    sa.Column('total_high', sa.Float(), nullable=True),
    sa.Column('renovation_tier', sa.String(length=16), nullable=True),
    sa.Column('breakdown', sa.JSON(), nullable=False),
    sa.Column('assumptions', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cost_estimates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cost_estimates_property_id'), ['property_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_cost_estimates_total_mid'), ['total_mid'], unique=False)

    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('document_url', sa.String(length=1000), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('document_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('issue', sa.String(length=80), nullable=True),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('matched_text', sa.Text(), nullable=True),
    sa.Column('local_path', sa.String(length=500), nullable=True),
    sa.Column('ocr_used', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_documents_property_id'), ['property_id'], unique=False)

    op.create_table('images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=False),
    sa.Column('local_path', sa.String(length=500), nullable=True),
    sa.Column('phash', sa.String(length=32), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('visual_features', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('property_id', 'url', name='uq_image_property_url')
    )
    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_images_phash'), ['phash'], unique=False)
        batch_op.create_index(batch_op.f('ix_images_property_id'), ['property_id'], unique=False)

    op.create_table('observations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=True),
    sa.Column('url', sa.String(length=1000), nullable=False),
    sa.Column('scraped_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('price_type', sa.String(length=16), nullable=True),
    sa.Column('price_raw', sa.String(length=200), nullable=True),
    sa.Column('land_sqm', sa.Float(), nullable=True),
    sa.Column('living_sqm', sa.Float(), nullable=True),
    sa.Column('usable_sqm', sa.Float(), nullable=True),
    sa.Column('year_built', sa.Integer(), nullable=True),
    sa.Column('town', sa.String(length=160), nullable=True),
    sa.Column('postcode', sa.String(length=16), nullable=True),
    sa.Column('listing_visible', sa.Boolean(), nullable=False),
    sa.Column('http_status', sa.Integer(), nullable=True),
    sa.Column('listing_text_hash', sa.String(length=64), nullable=True),
    sa.Column('image_hashes', sa.JSON(), nullable=False),
    sa.Column('source_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('raw', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['search_runs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('observations', schema=None) as batch_op:
        batch_op.create_index('ix_observations_prop_time', ['property_id', 'scraped_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_observations_property_id'), ['property_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_observations_scraped_at'), ['scraped_at'], unique=False)

    op.create_table('price_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('old_price', sa.Float(), nullable=True),
    sa.Column('new_price', sa.Float(), nullable=True),
    sa.Column('delta_abs', sa.Float(), nullable=True),
    sa.Column('delta_pct', sa.Float(), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('price_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_price_history_property_id'), ['property_id'], unique=False)

    op.create_table('property_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=False),
    sa.Column('external_id', sa.String(length=200), nullable=True),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('is_primary_source', sa.Boolean(), nullable=False),
    sa.Column('is_best', sa.Boolean(), nullable=False),
    sa.Column('first_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_listing_visible', sa.Boolean(), nullable=False),
    sa.Column('source_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('contact_name', sa.String(length=200), nullable=True),
    sa.Column('contact_kind', sa.String(length=32), nullable=True),
    sa.Column('contact_detail', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'url', name='uq_property_source_url')
    )
    with op.batch_alter_table('property_sources', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_property_sources_property_id'), ['property_id'], unique=False)

    op.create_table('reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('week_label', sa.String(length=32), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=True),
    sa.Column('profile_hash', sa.String(length=32), nullable=True),
    sa.Column('summary', sa.JSON(), nullable=False),
    sa.Column('markdown', sa.Text(), nullable=True),
    sa.Column('html', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['search_runs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('profile_hash', sa.String(length=32), nullable=False),
    sa.Column('fit_score', sa.Float(), nullable=False),
    sa.Column('deal_score', sa.Float(), nullable=False),
    sa.Column('hidden_score', sa.Float(), nullable=False),
    sa.Column('freshness_score', sa.Float(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('final_score', sa.Float(), nullable=False),
    sa.Column('capital_risk', sa.String(length=16), nullable=True),
    sa.Column('rejected', sa.Boolean(), nullable=False),
    sa.Column('reject_reasons', sa.JSON(), nullable=False),
    sa.Column('flags', sa.JSON(), nullable=False),
    sa.Column('breakdown', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('property_id', 'profile_hash', name='uq_score_property_profile')
    )
    with op.batch_alter_table('scores', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scores_final_score'), ['final_score'], unique=False)
        batch_op.create_index(batch_op.f('ix_scores_profile_hash'), ['profile_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_scores_property_id'), ['property_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_scores_rejected'), ['rejected'], unique=False)

    op.create_table('status_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('old_status', sa.String(length=24), nullable=True),
    sa.Column('new_status', sa.String(length=24), nullable=False),
    sa.Column('change_kind', sa.String(length=32), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('run_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['search_runs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('status_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_status_history_property_id'), ['property_id'], unique=False)

    op.create_table('verification_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('checked_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=False),
    sa.Column('outcome', sa.String(length=16), nullable=False),
    sa.Column('http_status', sa.Integer(), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('verification_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_verification_events_property_id'), ['property_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('verification_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_verification_events_property_id'))

    op.drop_table('verification_events')
    with op.batch_alter_table('status_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_status_history_property_id'))

    op.drop_table('status_history')
    with op.batch_alter_table('scores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scores_rejected'))
        batch_op.drop_index(batch_op.f('ix_scores_property_id'))
        batch_op.drop_index(batch_op.f('ix_scores_profile_hash'))
        batch_op.drop_index(batch_op.f('ix_scores_final_score'))

    op.drop_table('scores')
    op.drop_table('reports')
    with op.batch_alter_table('property_sources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_property_sources_property_id'))

    op.drop_table('property_sources')
    with op.batch_alter_table('price_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_price_history_property_id'))

    op.drop_table('price_history')
    with op.batch_alter_table('observations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_observations_scraped_at'))
        batch_op.drop_index(batch_op.f('ix_observations_property_id'))
        batch_op.drop_index('ix_observations_prop_time')

    op.drop_table('observations')
    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_images_property_id'))
        batch_op.drop_index(batch_op.f('ix_images_phash'))

    op.drop_table('images')
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_documents_property_id'))

    op.drop_table('documents')
    with op.batch_alter_table('cost_estimates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cost_estimates_total_mid'))
        batch_op.drop_index(batch_op.f('ix_cost_estimates_property_id'))

    op.drop_table('cost_estimates')
    with op.batch_alter_table('sources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sources_key'))

    op.drop_table('sources')
    op.drop_table('search_runs')
    with op.batch_alter_table('search_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_search_profiles_profile_hash'))

    op.drop_table('search_profiles')
    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_properties_verification_status'))
        batch_op.drop_index(batch_op.f('ix_properties_user_state'))
        batch_op.drop_index(batch_op.f('ix_properties_town'))
        batch_op.drop_index(batch_op.f('ix_properties_public_id'))
        batch_op.drop_index(batch_op.f('ix_properties_property_type'))
        batch_op.drop_index(batch_op.f('ix_properties_price'))
        batch_op.drop_index(batch_op.f('ix_properties_postcode'))
        batch_op.drop_index(batch_op.f('ix_properties_listing_status'))
        batch_op.drop_index(batch_op.f('ix_properties_land_sqm'))
        batch_op.drop_index('ix_properties_geo')
        batch_op.drop_index(batch_op.f('ix_properties_fingerprint'))
        batch_op.drop_index(batch_op.f('ix_properties_distance_air_km'))
        batch_op.drop_index('ix_properties_active')

    op.drop_table('properties')
    with op.batch_alter_table('geo_cache', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_geo_cache_key'))

    op.drop_table('geo_cache')
    # ### end Alembic commands ###
